openapi: '3.0.3'
info:
  title: Students API
  version: '1.0'
servers:
  - url: https://localhost/api/v1
paths:
  /students:
    get:
      summary: List all students
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/studentResponse'
components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email
        age:
          type: integer
          minimum: 0
        department:
          type: string
        level:
          type: string
          description: e.g. "100", "200", "300", "400", "500"
        profilePicture:
          type: string
          format: uri
          description: URL to the student's profile picture
      required:
        - id
        - name
        - email

  
    studentResponse:
      type: array
      items:
        $ref: '#/components/schemas/Student'